### ISSUE TITLE
Discord : Post a message - People tags doesn't work

### ISSUE THREAD

**Issue by Progi1984** [riderx/indiemakers#152]
When you post your last message from Discord `im post ajouter...`, if you tag people on Discord, the post on IndieMakers lose the people tag.

**Comment by riderx** [comment]
@Progi1984 it seems we can link to user account with `https://discord.com/users/304619871537201162` 
I have to find they user name in discord API and replace it to make the link work

**Comment by riderx** [comment]
Fixed last week :)
